<?php

use Illuminate\Database\Seeder;
use Carbon\Carbon;
use Illuminate\Support\Facades\DB;
class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('products')->insert([
            [
                'brand'=>'Yamaha',
                'model' =>'Xmax',
                'motor'=>'125',
                'year' => '2018',
                'city' => 'madrid',
                'required_license'=>'A1',
                'status_for_renting'=>'enabled',
                'price'=>'80',
                'description'=>'Moto scooter perfecta para moverte por la ciudad y evitar el trafico',
                'category_id'=>1,
                'user_id'=>3,
                'detach'=>false,
                'permit_circulation_image_path' => '1592419848-permiso_de_circulacion1592418396-permiso_de_circulacion.jpg',
                'image_path_1' => '1592417766-yamaha_xmax_125.jpg',
                'image_path_2' => '1592418373-yamaha_xmax2_125.jpg',
                'image_path_3' => '1592418380-yamaha_xmax3_125.jpg',
                'image_path_4' => '1592418387-yamaha_xmax4_125.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            
            [
                'brand'=>'Suzuki',
                'model' =>'Dr-650',
                'motor'=>'650',
                'year' => '2018',
                'city' => 'madrid',
                'required_license'=>'A2',
                'status_for_renting'=>'enabled',
                'price'=>'110',
                'description'=>'Excelente motard para llevar al terreno como al a calle',
                'category_id'=>3,
                'user_id'=>4,
                'detach'=>false,
                'permit_circulation_image_path' => '1592419848-permiso_de_circulacion.jpg',
                'image_path_1' => '1592707516-dr650-1.jpg',
                'image_path_2' => '1592707522-dr650-2.jpg',
                'image_path_3' => '1592707531-dr650-3.jpg',
                'image_path_4' => '1592707541-dr650-4.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'brand'=>'Honda',
                'model' =>'CB125',
                'motor'=>'125',
                'year' => '2018',
                'city' => 'madrid',
                'required_license'=>'A1',
                'status_for_renting'=>'enabled',
                'price'=>'75',
                'description'=>'una moto muy versatil para disfrutar al maximo de la movilidad en dos ruedas para cualquier persona',
                'category_id'=>2,
                'user_id'=>5,
                'detach'=>false,
                'permit_circulation_image_path' => '1592419848-permiso_de_circulacion.jpg',
                'image_path_1' => '1592738434-hondaCB1-125.jpg',
                'image_path_2' => '1592738427-hondaCB2-125.jpg',
                'image_path_3' => '1592738421-hondaCB3-125.jpg',
                'image_path_4' => '1592738440-hondaCB4-125.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'brand'=>'Kawasaki',
                'model' =>'Versys',
                'motor'=>'650',
                'year' => '2018',
                'city' => 'getafe',
                'required_license'=>'A2',
                'status_for_renting'=>'enabled',
                'price'=>'130',
                'description'=>'una moto muy potente perfecta para usar y llevarla a donde quieras, ofrece una posicion de conduion erguida',
                'category_id'=>5,
                'user_id'=>6,
                'detach'=>true,
                'permit_circulation_image_path' => '1592419848-permiso_de_circulacion1592419848-permiso_de_circulacion.jpg',
                'image_path_1' => '1592419812-versys.jpg',
                'image_path_2' => '1592419821-versys_2.jpg',
                'image_path_3' => '1592419891-versys_3.jpg',
                'image_path_4' => '1592419840-versys_4.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'brand'=>'Yamaha',
                'model' =>'MT-10',
                'motor'=>'1000',
                'year' => '2018',
                'city' => 'madrid',
                'required_license'=>'A',
                'status_for_renting'=>'enabled',
                'price'=>'280',
                'description'=>'excelente moto que ofrece una experiencia de conduccion unica para conductores expertos de motocicletas',
                'category_id'=>6,
                'user_id'=>7,
                'detach'=>true,
                'permit_circulation_image_path' => '1592419848-permiso_de_circulacion.jpg',
                'image_path_1' => '1592738803-YamahaMT10-1.jpg',
                'image_path_2' => '1592738816-YamahaMT10-2.jpg',
                'image_path_3' => '1592738823-YamahaMT10-3.jpg',
                'image_path_4' => '1592738830-YamahaMT10-4.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'brand'=>'Susuki',
                'model' =>'Hayabusa',
                'motor'=>'1200',
                'year' => '2018',
                'city' => 'Valencia',
                'required_license'=>'A',
                'status_for_renting'=>'enabled',
                'price'=>'300',
                'description'=>'exclente moto para viajes largos con una potencia excepcional',
                'category_id'=>4,
                'user_id'=>8,
                'detach'=>false,
                'permit_circulation_image_path' => '1592419848-permiso_de_circulacion.jpg',
                'image_path_1' => '1592739305-hayabusa-1.jpg',
                'image_path_2' => '1592739312-hayabusa-2.jpg',
                'image_path_3' => '1592739317-hayabusa-3.jpg',
                'image_path_4' => '1592739327-hayabusa-4.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'brand'=>'Yamaha',
                'model' =>'R1',
                'motor'=>'1000',
                'year' => '2018',
                'city' => 'barcelona',
                'required_license'=>'A',
                'status_for_renting'=>'enabled',
                'price'=>'170',
                'description'=>'una excelente moto con diseño clasico deportivo',
                'category_id'=>8,
                'user_id'=>9,
                'detach'=>false,
                'permit_circulation_image_path' => '1592419848-permiso_de_circulacion.jpg',
                'image_path_1' => '1592739717-yamaha_r1-1.jpg',
                'image_path_2' => '1592739726-yamaha_r1-3.jpg',
                'image_path_3' => '1592739731-yamaha_r1-2.jpg',
                'image_path_4' => '1592739735-yamaha_r1-4.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'brand'=>'BMW',
                'model' =>'S1000RR',
                'motor'=>'1000',
                'year' => '2018',
                'city' => 'bilbao',
                'required_license'=>'A',
                'status_for_renting'=>'enabled',
                'price'=>'230',
                'description'=>'para los amantes de la velocidad, solo conductores experimentados',
                'category_id'=>8,
                'user_id'=>10,
                'detach'=>false,
                'permit_circulation_image_path' => '1592419848-permiso_de_circulacion.jpg',
                'image_path_1' => '1592740140-bmw-s1000rr1.jpg',
                'image_path_2' => '1592740144-bmw-s1000rr2.jpg',
                'image_path_3' => '1592740151-bmw-s1000rr3.jpg',
                'image_path_4' => '1592740157-bmw-s1000rr4.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'brand'=>'Aprillia',
                'model' =>'Dorsoduro 900',
                'motor'=>'900',
                'year' => '2019',
                'city' => 'madrid',
                'required_license'=>'A',
                'status_for_renting'=>'enabled',
                'price'=>'90',
                'description'=>'para los amantes de la velocidad, solo conductores experimentados',
                'category_id'=>3,
                'user_id'=>11,
                'detach'=>true,
                'permit_circulation_image_path' => '1592419848-permiso_de_circulacion.jpg',
                'image_path_1' => '1592740377-aprilia-4.jpg',
                'image_path_2' => '1592740385-aprilia-1.jpg',
                'image_path_3' => '1592740390-aprilia-2.jpg',
                'image_path_4' => '1592740394-aprilia-3.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'brand'=>'Benelli',
                'model' =>'Trk 502',
                'motor'=>'500',
                'year' => '2020',
                'city' => 'galicia',
                'required_license'=>'A2',
                'status_for_renting'=>'enabled',
                'price'=>'60',
                'description'=>'para los amantes de la velocidad, solo conductores experimentados',
                'category_id'=>5,
                'user_id'=>12,
                'detach'=>false,
                'permit_circulation_image_path' => '1592419848-permiso_de_circulacion.jpg',
                'image_path_1' => '1592740758-trk-1.jpg',
                'image_path_2' => '1592740765-trk-2.jpg',
                'image_path_3' => '1592740771-trk-3.jpg',
                'image_path_4' => '1592740774-trk-4.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'brand'=>'Ducati',
                'model' =>'Diavel',
                'motor'=>'1200',
                'year' => '2020',
                'city' => 'getafe',
                'required_license'=>'A',
                'status_for_renting'=>'enabled',
                'price'=>'90',
                'description'=>'para los amantes de la velocidad, solo conductores experimentados',
                'category_id'=>7,
                'user_id'=>13,
                'detach'=>false,
                'permit_circulation_image_path' => '1592419848-permiso_de_circulacion.jpg',
                'image_path_1' => '1592741110-diavel-1.jpg',
                'image_path_2' => '1592741114-diavel-2.jpg',
                'image_path_3' => '1592741124-diavel-3.jpg',
                'image_path_4' => '1592741124-diavel-4.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'brand'=>'Keeway',
                'model' =>'Rkf',
                'motor'=>'125',
                'year' => '2019',
                'city' => 'Sevilla',
                'required_license'=>'A1',
                'status_for_renting'=>'enabled',
                'price'=>'90',
                'description'=>'para los amantes de la velocidad, solo conductores experimentados',
                'category_id'=>2,
                'user_id'=>14,
                'detach'=>true,
                'permit_circulation_image_path' => '1592419848-permiso_de_circulacion.jpg',
                'image_path_1' => '1592741383-rkf-1.jpg',
                'image_path_2' => '1592741394-rkf-2.jpg',
                'image_path_3' => '1592741401-rkf-3.jpg',
                'image_path_4' => '1592741408-rkf-4.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'brand'=>'Triumph',
                'model' =>'Tiger',
                'motor'=>'900',
                'year' => '2016',
                'city' => 'Cordoba',
                'required_license'=>'A',
                'status_for_renting'=>'enabled',
                'price'=>'90',
                'description'=>'para los amantes de la velocidad, solo conductores experimentados',
                'category_id'=>5,
                'user_id'=>15,
                'detach'=>false,
                'permit_circulation_image_path' => '1592419848-permiso_de_circulacion.jpg',
                'image_path_1' => '1592741773-triumph-1.jpg',
                'image_path_2' => '1592741781-triumph-4.jpg',
                'image_path_3' => '1592741790-triumph-3.jpg',
                'image_path_4' => '1592741796-triumph-2.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'brand'=>'Moto Guzzi',
                'model' =>'MGX-21',
                'motor'=>'1200',
                'year' => '2020',
                'city' => 'getafe',
                'required_license'=>'A',
                'status_for_renting'=>'enabled',
                'price'=>'90',
                'description'=>'para los amantes de la velocidad, solo conductores experimentados',
                'category_id'=>7,
                'user_id'=>16,
                'detach'=>false,
                'permit_circulation_image_path' => '1592419848-permiso_de_circulacion.jpg',
                'image_path_1' => '1592742020-mg-1.jpg',
                'image_path_2' => '1592742030-mg-2.jpg',
                'image_path_3' => '1592742035-mg-3.jpg',
                'image_path_4' => '1592742041-mg-4.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'brand'=>'Piaggio',
                'model' =>'MP3',
                'motor'=>'300',
                'year' => '2019',
                'city' => 'girona',
                'required_license'=>'A2',
                'status_for_renting'=>'enabled',
                'price'=>'50',
                'description'=>'para los amantes de la velocidad, solo conductores experimentados',
                'category_id'=>1,
                'user_id'=>17,
                'detach'=>true,
                'permit_circulation_image_path' => '1592419848-permiso_de_circulacion.jpg',
                'image_path_1' => '1592742195-mp3-1.jpg',
                'image_path_2' => '1592742202-mp3-2.jpg',
                'image_path_3' => '1592742211-mp3-3.jpg',
                'image_path_4' => '1592742218-mp3-4.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'brand'=>'KTM',
                'model' =>'Duke',
                'motor'=>'800',
                'year' => '2019',
                'city' => 'zaragoza',
                'required_license'=>'A',
                'status_for_renting'=>'enabled',
                'price'=>'90',
                'description'=>'para los amantes de la velocidad, solo conductores experimentados',
                'category_id'=>6,
                'user_id'=>18,
                'detach'=>false,
                'permit_circulation_image_path' => '1592419848-permiso_de_circulacion.jpg',
                'image_path_1' => '1592742674-duke-1.jpg',
                'image_path_2' => '1592742681-duke-2.jpg',
                'image_path_3' => '1592742689-duke-3.jpg',
                'image_path_4' => '1592742696-duke-4.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'brand'=>'Bajaj',
                'model' =>'Dominar',
                'motor'=>'400',
                'year' => '2019',
                'city' => 'salamanca',
                'required_license'=>'A2',
                'status_for_renting'=>'enabled',
                'price'=>'90',
                'description'=>'para los amantes de la velocidad, solo conductores experimentados',
                'category_id'=>2,
                'user_id'=>19,
                'detach'=>false,
                'permit_circulation_image_path' => '1592419848-permiso_de_circulacion.jpg',
                'image_path_1' => '1592742936-bajaj-1.jpg',
                'image_path_2' => '1592742946-bajaj-2.jpg',
                'image_path_3' => '1592742948-bajaj-3.jpg',
                'image_path_4' => '1592742950-bajaj-4.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'brand'=>'Suzuki',
                'model' =>'Vstrom',
                'motor'=>'650',
                'year' => '2020',
                'city' => 'valencia',
                'required_license'=>'A2',
                'status_for_renting'=>'enabled',
                'price'=>'90',
                'description'=>'para los amantes de la velocidad, solo conductores experimentados',
                'category_id'=>5,
                'user_id'=>20,
                'detach'=>true,
                'permit_circulation_image_path' => '1592419848-permiso_de_circulacion.jpg',
                'image_path_1' => '1592743308-vstrom-1.jpg',
                'image_path_2' => '1592743317-vstrom3.jpg',
                'image_path_3' => '1592743322-vstrom-2.jpg',
                'image_path_4' => '1592743330-vstrom-4.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ]);
    }
}
