<?php

use Illuminate\Database\Seeder;
use Carbon\Carbon;
use Illuminate\Support\Facades\DB;
class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('products')->insert([
            [
                'brand'=>'Yamaha',
                'model' =>'Xmax',
                'motor'=>'125',
                'year' => '2018',
                'city' => 'madrid',
                'required_license'=>'A1',
                'status_for_renting'=>'enabled',
                'price'=>'80',
                'description'=>'Moto scooter perfecta para moverte por la ciudad y evitar el trafico',
                'category_id'=>1,
                'user_id'=>3,
                'permit_circulation_image_path' => '1592418396-permiso_de_circulacion.jpg',
                'image_path_1' => '1592417766-yamaha_xmax_125.jpg',
                'image_path_2' => '1592418373-yamaha_xmax2_125.jpg',
                'image_path_3' => '1592418380-yamaha_xmax3_125.jpg',
                'image_path_4' => '1592418387-yamaha_xmax4_125.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            
            [
                'brand'=>'Suzuki',
                'model' =>'Dr-650',
                'motor'=>'650',
                'year' => '2018',
                'city' => 'madrid',
                'required_license'=>'A2',
                'status_for_renting'=>'enabled',
                'price'=>'110',
                'description'=>'Excelente motard para llevar al terreno como al a calle',
                'category_id'=>3,
                'user_id'=>4,
                'permit_circulation_image_path' => null,
                'image_path_1' => null,
                'image_path_2' => null,
                'image_path_3' => null,
                'image_path_4' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'brand'=>'Honda',
                'model' =>'CB125',
                'motor'=>'125',
                'year' => '2018',
                'city' => 'madrid',
                'required_license'=>'A1',
                'status_for_renting'=>'enabled',
                'price'=>'75',
                'description'=>'una moto muy versatil para disfrutar al maximo de la movilidad en dos ruedas para cualquier persona',
                'category_id'=>2,
                'user_id'=>5,
                'permit_circulation_image_path' => null,
                'image_path_1' => null,
                'image_path_2' => null,
                'image_path_3' => null,
                'image_path_4' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'brand'=>'Kawasaki',
                'model' =>'Versys',
                'motor'=>'650',
                'year' => '2018',
                'city' => 'getafe',
                'required_license'=>'A2',
                'status_for_renting'=>'enabled',
                'price'=>'130',
                'description'=>'una moto muy potente perfecta para usar y llevarla a donde quieras, ofrece una posicion de conduion erguida',
                'category_id'=>5,
                'user_id'=>3,
                'permit_circulation_image_path' => '1592419848-permiso_de_circulacion.jpg',
                'image_path_1' => '1592419812-versys.jpg',
                'image_path_2' => '1592419821-versys_2.jpg',
                'image_path_3' => '1592419891-versys_3.jpg',
                'image_path_4' => '1592419840-versys_4.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'brand'=>'Yamaha',
                'model' =>'MT-10',
                'motor'=>'1000',
                'year' => '2018',
                'city' => 'madrid',
                'required_license'=>'A',
                'status_for_renting'=>'enabled',
                'price'=>'280',
                'description'=>'excelente moto que ofrece una experiencia de conduccion unica para conductores expertos de motocicletas',
                'category_id'=>6,
                'user_id'=>4,
                'permit_circulation_image_path' => null,
                'image_path_1' => null,
                'image_path_2' => null,
                'image_path_3' => null,
                'image_path_4' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'brand'=>'Kawasaki',
                'model' =>'ZZR',
                'motor'=>'1400',
                'year' => '2018',
                'city' => 'Valencia',
                'required_license'=>'A',
                'status_for_renting'=>'enabled',
                'price'=>'300',
                'description'=>'exclente moto para viajes largos con una potencia excepcional',
                'category_id'=>4,
                'user_id'=>5,
                'permit_circulation_image_path' => null,
                'image_path_1' => null,
                'image_path_2' => null,
                'image_path_3' => null,
                'image_path_4' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'brand'=>'Yamaha',
                'model' =>'XSR900',
                'motor'=>'900',
                'year' => '2018',
                'city' => 'barcelona',
                'required_license'=>'A',
                'status_for_renting'=>'enabled',
                'price'=>'170',
                'description'=>'una excelente moto con diseño clasico deportivo',
                'category_id'=>7,
                'user_id'=>5,
                'permit_circulation_image_path' => null,
                'image_path_1' => null,
                'image_path_2' => null,
                'image_path_3' => null,
                'image_path_4' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'brand'=>'BMW',
                'model' =>'S1000RR',
                'motor'=>'1000',
                'year' => '2018',
                'city' => 'bilbao',
                'required_license'=>'A',
                'status_for_renting'=>'enabled',
                'price'=>'230',
                'description'=>'para los amantes de la velocidad, solo conductores experimentados',
                'category_id'=>8,
                'user_id'=>5,
                'permit_circulation_image_path' => null,
                'image_path_1' => null,
                'image_path_2' => null,
                'image_path_3' => null,
                'image_path_4' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

        ]);
    }
}
